apiVersion: apps/v1
kind: Deployment
metadata:
  name: solvertest
  labels:
    app: solvertest
spec:
  replicas: 1
  selector:
    matchLabels:
        app: solvertest
  template:
    metadata:
      labels:
        app: solvertest
    spec:
      containers:
      - name: enva
        image: riedbt/solvertest:0.3
        imagePullPolicy: Always
        env:
        - name: JVM_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -Xms7G -Xmx8G"